# Linear Regression

In this notebook, we will go through linear regression in details. First we need some setup:

In [2]:
library(tidyverse)

options(repr.plot.width=8, repr.plot.height=5)

url <- "https://raw.githubusercontent.com/jgendron/com.packtpub.intro.r.bi/master/Chapter4-LinearRegressionforBusiness/data/Ch4_marketing.csv"
adverts <- read.csv(url)

── Attaching packages ─────────────────────────────────────── tidyverse 1.2.1 ──
✔ ggplot2 2.2.1     ✔ purrr   0.2.4
✔ tibble  1.4.1     ✔ dplyr   0.7.4
✔ tidyr   0.7.2     ✔ stringr 1.3.1
✔ readr   1.1.1     ✔ forcats 0.2.0
── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()


As we have seem when talking about correlation there might be a linear relationship between two variables such as `hwy` and `displ` in the `mpg` dataset. In such a case how do we best find such a line?

In [3]:
ggplot(data = mpg, mapping = aes(x = displ, y = hwy)) + ylim(10, 45) +
  geom_point()
ggplot(data = mpg, mapping = aes(x = displ, y = hwy)) + ylim(10, 45) +
  geom_point() +  geom_smooth(method = "lm", se = FALSE)

The answer is linear regression...

There are two types of linear regression, the one being an extension of the other:
* *Simple Linear Regression*
    - about finding a linear relationship between a **response**(/dependent) variable `y` and a **predictor**(/independent) variable `x`.
    - In math, we want to find `a` and `b` such that the line `y = a*x + b` is the **best** line that **fits** some given data
* *Multiple Linear Regression*
    - about finding a linear relationship between a **response**(/dependent) variable `y` and some **predictor**(/independent) variables `x_1`, `x_2`, ..., `x_n`.
    -  In math, we want to find `a_0, a_1, a_2, ..., a_n` such that the model `y = a_0 + a_1 * x_1 + a_2 * x_2 + ... + a_n * x_n` is the **best** model that **fits** some given data
    
Having fitted a linear model, i.e. fund particular values for `a_0, a_1, a_2, ..., a_n`, the function `f(x_1, x_2, ..., x_n) = a_0 + a_1 * x_1 + a_2 * x_2 + ... + a_n * x_n` returns a predicted value of `y` for any given set of values for `x_1, x_2, ..., x_n`. But how do we fit such a linear model and what does best mean?

The best model is the one for which the **root-mean-square distance** between the predicted values and response values is minimal. (For each pair of actual and predicted response values we take the difference between them and square it. We them sum all these squared distances and take the square root of it.)


In [4]:
fit <- lm(mpg ~ wt, mtcars)
ggplot(data = mtcars, mapping = aes(x = wt, y = mpg)) +
  geom_point() + geom_smooth(method = "lm", se = FALSE) +
  geom_segment(data = cbind(mtcars, pred=predict(fit, mtcars)), aes(yend = pred, xend = wt), color = "red")

### A simple example

A car's fuel consumption (mpg) might be a function of its weight (wt) and the number of cylinders its engine contains (cyl):

    `mpg = a_0 + a_1 * wt + a_2 * cyl`

### Fuel consumption (mpg) as a linear function of weight (wt)

* The family of models is: `mpg = a_0 + a_1 * wt`
* But how do we find `a_0` and `a_1`? (Read them of the following graph?!?)

In [5]:
ggplot(data = mtcars, mapping = aes(x = wt, y = mpg)) + scale_y_continuous(limits = c(5,35)) +
  geom_point()
ggplot(data = mtcars, mapping = aes(x = wt, y = mpg)) + scale_y_continuous(limits = c(5,35)) +
  geom_point() + geom_smooth(method = "lm")

### Fitting linear models in R - the `lm` function

Luckily, R has a function for fitting such linear models (of course!)

This allows us to find `a_0` and `a_1` in `mpg = a_0 + a_1 * wt` based on the `mtcars` data set

The function is simply called `lm` for "linear models". As its two main arguments it takes a formula specifying the model you want to fit and the dataset to which you want to fit the model. Here is an example of how to fit the model just mentioned:

In [6]:
# ?lm
lm(formula = mpg ~ wt, data = mtcars)



Call:
lm(formula = mpg ~ wt, data = mtcars)

Coefficients:
(Intercept)           wt  
     37.285       -5.344  


Here "Call" tells you what model and data you used as input and the "Coefficients" tells you the "a_0" and "a_1" of your linear regression:

`mpg = a_0 + a_1 * wt`

`a_1` is also referred to as "the slope" and `a_0` as "the intercept".

Putting in the number we get that:

`mpg = -5.344 * wt + 37.285`

The slope (`a_1`) can be interpreted as: *"For every time a car weighs 1000lbs more, its miles per gallon goes down by 5.344"*. The intercept can be interpreted as: *"If a car weighs 0lbs, it will go 37.285 miles per gallon!?"*. As a car cannot weigh 0lbs, we should be careful in interpreting the intersect in this case.

Finally, let us visualize the model wrt. the data, that is, let us plot the data together with the line that we found as the model:

In [7]:
ggplot(mtcars) + geom_point(aes(x = wt, y = mpg)) +
geom_line(aes(x = wt, y = -5.344 * wt + 37.285), color = "red")

### *Exercise*

The marketing data of chapter 4 of the book "Introduction to R for Business Intelligence" by Jay Gendron is loaded into a data frame called `adverts`.

Use this data to fit the following linear regression model:

`revenues = a * marketing_total + b`

(or `revenues = a_0 + a_1 * marketing_total`)

- What are the values for `a` and `b`?
- How should you interpret the values for `a` and `b`?

In [8]:
lm(formula = revenues ~ marketing_total - 1, data = adverts)


Call:
lm(formula = revenues ~ marketing_total - 1, data = adverts)

Coefficients:
marketing_total  
         0.1661  


In [9]:
ggplot(data = adverts) + geom_point(aes(x = marketing_total, y = revenues)) +
geom_line(aes(x = marketing_total, y =32.00670 + 0.05193 * marketing_total), color = "yellow") +
geom_line(aes(x = marketing_total, y =0.1661 * marketing_total), color = "green")

## Multiple linear regression in R

We can also deal with multiple predictor variables. Recall the model family: a car's fuel consumption (`mpg`) as a function of its weight (`wt`) and the number of cylinders its engine contains (`cyl`):

`mpg = a_0 + a_1 * wt + a_2 * cyl`

In R we can fit this model by:

In [10]:
lm(formula = mpg ~ wt + cyl, data = mtcars)


Call:
lm(formula = mpg ~ wt + cyl, data = mtcars)

Coefficients:
(Intercept)           wt          cyl  
     39.686       -3.191       -1.508  


### Other models

There are a lot of options for specifying other models using the `lm` function. Let us go through a few of them.

First, we can fit a model without an intercept (making the hard assumption that the intercept is zero). For instance, we can fit the model:

`mpg = a_1 * wt + a_2 * cyl`

In [11]:
lm(formula = mpg ~ wt + cyl - 1, data = mtcars)


Call:
lm(formula = mpg ~ wt + cyl - 1, data = mtcars)

Coefficients:
   wt    cyl  
1.174  2.187  


We can also use products of variables as input to models, such as in the model:

`mpg = a_0 + a_1 * wt + a_2 * cyl * displ`

In [12]:
lm(formula = mpg ~ wt + I(cyl * disp), data = mtcars)


Call:
lm(formula = mpg ~ wt + I(cyl * disp), data = mtcars)

Coefficients:
  (Intercept)             wt  I(cyl * disp)  
    34.282352      -3.522725      -0.001763  


The `I` around `cyl * displ` is needed to get only the product of these two variables in the model. Look what happens if we leave it out:

In [13]:
lm(formula = mpg ~ wt + cyl * disp, data = mtcars)


Call:
lm(formula = mpg ~ wt + cyl * disp, data = mtcars)

Coefficients:
(Intercept)           wt          cyl         disp     cyl:disp  
   49.55195     -2.73695     -3.00543     -0.08670      0.01107  


In this case we actually fitted the model:

`mpg = a_0 + a_1 * wt + a_2 * cyl + a_4 * disp + a_5 * cyl * displ`

### Linear models with categorical variables

We can also use categorical variables as predictor variables in linear regression. However, for this to work properly, the categorical variables need to be given in the factor data type in R. As gear is a categorical variable, we can make it into a factor and use it as a predictor variable in the following model:

`mpg = a_0 + a_1 * wt + a_2 * gear`

In [14]:
mtcars$gear <- as.factor(mtcars$gear)
lm(formula = mpg ~ wt + gear, data = mtcars)


Call:
lm(formula = mpg ~ wt + gear, data = mtcars)

Coefficients:
(Intercept)           wt        gear4        gear5  
    35.2156      -4.9090       2.1631      -0.9121  


What actually happened here is that R split the model `mpg = a_0 + a_1 * wt + a_2 * gear` into the model `mpg = a_0 + a_1 * wt + a_2 * gear4 + a_3 * gear5`, as the possible values of `gear` are `3, 4, 5`.

Thus, we get that:
- If `gear` is 3, `mpg = a_0 + a_1 * wt`
- If `gear` is 4, `mpg = a_0 + a_1 * wt + a_2 * gear4`
- If `gear` is 5, `mpg = a_0 + a_1 * wt + a_3 * gear5`

### *Exercise*

For the marketing data in the data frame `adverts` fit a multiple linear regression with `revenues` as the response variable and :

`revenues = a_0 + a_1 * google_adwords + a_2 * facebook + a_3 * twitter`

- What are the values for a_0, a_1, a_2 and a_3?
- How should you interpret the values for a_0, a_1, a_2 and a_3?

In [15]:
lm(formula = revenues ~ google_adwords + facebook + twitter, data = adverts)


Call:
lm(formula = revenues ~ google_adwords + facebook + twitter, 
    data = adverts)

Coefficients:
   (Intercept)  google_adwords        facebook         twitter  
     29.545988        0.048384        0.197651        0.003889  


## Model predictions and errors

Once we have a model we can use it to predict new values of the response variable from values of the predictor variables. (Note, we will have the most confidence in predictions when predicting within the ranges of our predictor variables). Here is how to predict new values of our response variable from new predictor variable values using the model:

`mpg = a_0 + a_1 * wt + a_2 * disp`

In [31]:
model1 <- lm(formula = mpg ~ wt + disp, data = mtcars)
newdata <- data.frame(wt = 3, disp = 300)
predict.lm(model1, newdata, interval = "predict")


fit      lwr      upr     
1 19.59065 13.27774 25.90357

The `fit` is the predicted value of `mpg` for `wt` 3 (3,000lbs) and `disp` 300. The `lwr` and `upr` represent the lower and upper bounds of a 95% confidence interval of the prediction. That is if we make 100 predictions, 95 will fall within this interval. We can change it to a 99% confidence interval, for instance, in the following way:

In [17]:
predict.lm(model1, newdata, interval = "predict", level = 0.99)

fit      lwr      upr     
1 19.59065 11.08265 28.09866

Note how the confidence interval got bigger. As we want more certainty in our estimate, we also have to accept a larger interval of possible values!

If we don't want the confidence interval along with the prediction we can simply do:

In [18]:
predict(model1, newdata)

1 
19.59065

We can also make multiple predictions at the same time by just including more rows in the data frame `newdata`. Here is an example of that:

In [32]:
newdata <- data.frame(wt = c(3, 3.1, 3.2), disp = c(300, 290, 270))
newdata
predict(model1, newdata)

wt  disp
1 3.0 300 
2 3.1 290 
3 3.2 270

1        2        3 
19.59065 19.43282 19.45223

### Residuals

Residuals are the difference between the real values of the response variable and the predicted values of the response variable. In other words, the residuals of a model are the errors in predicting on the data used to train the model. Residuals plays an important role in statistics.

Visually, residuals are the vertical distance between the line (the predicted values) and the points in the following plot:

In [20]:
fit <- lm(mpg ~ wt, mtcars)
ggplot(data = mtcars, mapping = aes(x = wt, y = mpg)) +
  geom_point() + geom_smooth(method = "lm", se = FALSE) +
  geom_segment(data = cbind(mtcars, pred=predict(fit, mtcars)), aes(yend = pred, xend = wt), color = "red")

We can also get the residuals from the fitted model `fit` by `fit$residuals`:

In [21]:
fit$residuals

Mazda RX4       Mazda RX4 Wag          Datsun 710      Hornet 4 Drive 
         -2.2826106          -0.9197704          -2.0859521           1.2973499 
  Hornet Sportabout             Valiant          Duster 360           Merc 240D 
         -0.2001440          -0.6932545          -3.9053627           4.1637381 
           Merc 230            Merc 280           Merc 280C          Merc 450SE 
          2.3499593           0.2998560          -1.1001440           0.8668731 
         Merc 450SL         Merc 450SLC  Cadillac Fleetwood Lincoln Continental 
         -0.0502472          -1.8830236           1.1733496           2.1032876 
  Chrysler Imperial            Fiat 128         Honda Civic      Toyota Corolla 
          5.9810744           6.8727113           1.7461954           6.4219792 
      Toyota Corona    Dodge Challenger         AMC Javelin          Camaro Z28 
         -2.6110037          -2.9725862          -3.7268663          -3.4623553 
   Pontiac Firebird           Fiat X1-9       Porsche 914-2        Lotus Europa 
          2.4643670           0.3564263           0.1520430           1.2010593 
     Ford Pantera L        Ferrari Dino       Maserati Bora          Volvo 142E 
         -4.5431513          -2.7809399          -3.2053627          -1.0274952

Or we can calculate them ourselves in a data frame:

In [22]:
data.frame(wt = mtcars$wt, actual_mpg = mtcars$mpg, predicted_mpg = predict(fit, mtcars)) %>%
    mutate(residuals = predicted_mpg - actual_mpg)

wt    actual_mpg predicted_mpg residuals 
1  2.620 21.0       23.282611      2.2826106
2  2.875 21.0       21.919770      0.9197704
3  2.320 22.8       24.885952      2.0859521
4  3.215 21.4       20.102650     -1.2973499
5  3.440 18.7       18.900144      0.2001440
6  3.460 18.1       18.793255      0.6932545
7  3.570 14.3       18.205363      3.9053627
8  3.190 24.4       20.236262     -4.1637381
9  3.150 22.8       20.450041     -2.3499593
10 3.440 19.2       18.900144     -0.2998560
11 3.440 17.8       18.900144      1.1001440
12 4.070 16.4       15.533127     -0.8668731
13 3.730 17.3       17.350247      0.0502472
14 3.780 15.2       17.083024      1.8830236
15 5.250 10.4        9.226650     -1.1733496
16 5.424 10.4        8.296712     -2.1032876
17 5.345 14.7        8.718926     -5.9810744
18 2.200 32.4       25.527289     -6.8727113
19 1.615 30.4       28.653805     -1.7461954
20 1.835 33.9       27.478021     -6.4219792
21 2.465 21.5       24.111004      2.6110037
22 3.520 15.5       18.472586      2.9725862
23 3.435 15.2       18.926866      3.7268663
24 3.840 13.3       16.762355      3.4623553
25 3.845 19.2       16.735633     -2.4643670
26 1.935 27.3       26.943574     -0.3564263
27 2.140 26.0       25.847957     -0.1520430
28 1.513 30.4       29.198941     -1.2010593
29 3.170 15.8       20.343151      4.5431513
30 2.770 19.7       22.480940      2.7809399
31 3.570 15.0       18.205363      3.2053627
32 2.780 21.4       22.427495      1.0274952

### *Exercise*

For the multiple linear regression model trained previously:

`revenues = a_0 + a_1 * google_adwords + a_2 * facebook + a_3 * twitter`,

calculate the residuals in a data frame.

## When is a model a good model? - Checking model assumptions

Statistical models comes with assumptions that need to be satisfied for the model to be properly used. By "properly used", we mean, among other things, that the model make sense wrt. the data, that the statistical estimates of errors and uncertainty are correct, and that predictions based on the model behave as expected. (See also http://varianceexplained.org/r/kmeans-free-lunch/ for a good discussion on model assumptions.)

For linear regression these model assumptions are:
- Linearity
- Independence
- Normality
- Equal variance

Note that, even if the model assumptions are satisfied, the model might still be a poorly fit to the data, it might still not predict well enough in the range we want to predict and it might not make sense from a business perspective. This is important to keep in mind.

### Linearity

The linearity assumption is simply that the relationship between the predictor and response variables is linear. This assumption is often checked the easiest by looking at the scatterplot of the predictor variable and the response variable. If it looks like data fall close to a straight line, the assumption is meet. The previous plot of `mpg` and `wt` constitute such an example. Here is a case where the assumption is clearly violated:

In [23]:
x <- 1:30
y = x^3 + rnorm(30, 0, 200)
ggplot() + geom_point(aes(x = x, y = y)) + geom_smooth(aes(x = x, y = y), method = "lm", se = FALSE)

### Independence

This assumption amounts to all predictor variables being independent. If there is only one predictor variable this is trivially satisfied, of course.

In the case of multiple predictor variables, one can always check the correlation between the predictor variables and often it is enough that none of them are strongly correlated. (A little correlation is hard to avoid.) It is sometimes possible to argue from for independence based on knowledge of the data.

### Normality

This assumption is about the residuals and requires them to be normally distributed with mean zero. A natural way to check this is by plotting a histogram of the residuals. In the case of `mpg` and `wt` we get the following histogram:

In [24]:
ggplot() + geom_histogram(aes(fit$residuals), binwidth = 1)

It is a bit hard to tell whether this is a normal distribution. It is not completely unlikely though. We can also add more predictor variables and how to see a more normal distribution of our residuals:

In [25]:
model2 <- lm(data = mtcars, formula = mpg ~ wt + disp + cyl + gear)
ggplot() + geom_histogram(aes(model2$residuals), binwidth = 1)

Given that we have a limited number of data points in this case and there will always be some noise, this is fairly close to normal.

Another common plot used to test for normality is the Q-Q plot. In the case of the latest model, the plot looks like this:

In [33]:
qqnorm(model2$residuals, main = "Q-Q Plot of Residuals of model2")
qqline(model2$residuals)
plot(model2)

If the points fall close to the straight line, the residuals are normally distributed, which almost seems to be the case. If we look at the previous model that did also not satisfy linearity, we can see an example where the residuals are clearly not normally distributed:

In [27]:
x <- 1:30
y = x^3 + rnorm(30, 0, 200)
model_nonLin <- lm(formula = y ~ x)
ggplot() + geom_histogram(aes(model_nonLin$residuals), binwidth = 1000)
qqnorm(model_nonLin$residuals, main = "Q-Q Plot of Residuals of non-linear model")
qqline(model_nonLin$residuals)

### Equal variance

This assumption amounts to the variance in the residuals being constant. That is the variance in the residuals does not depend on the actual fitted values. That is the error in prediction is just as big when we predict the response variable to be 1 as when we predict it to be 10,000 (on average). This can be checked by plotting the residual against the predicted values. For the model `mpg ~ wt + disp + cyl + gear` we get:

In [28]:
ggplot() + geom_point(aes(x = predict(model2), y = model2$residuals))

Here is an example where there is clearly no equal variance:

In [34]:
x_2 <- 1:100
y_2 <- 1 + 2 * x + rnorm(100, 0, 0.5)*(1:100)
theModel <- lm(y_2 ~ x_2)
ggplot() + geom_point(aes(x = predict(theModel), y = theModel$residuals))

Warning message in 1 + 2 * x + rnorm(100, 0, 0.5) * (1:100):
“longer object length is not a multiple of shorter object length”

### *Exercise*

For the multiple linear regression model trained previously:

`revenues = a_0 + a_1 * google_adwords + a_2 * facebook + a_3 * twitter`,

check all the four model assumptions.

## Interpreting the output of `lm()`

The `summary` function can also be used on models to generate more information about the model and the fit:

In [30]:
model <- lm(formula = mpg ~ wt + disp, data = mtcars)
summary(model)


Call:
lm(formula = mpg ~ wt + disp, data = mtcars)

Residuals:
    Min      1Q  Median      3Q     Max 
-3.4087 -2.3243 -0.7683  1.7721  6.3484 

Coefficients:
            Estimate Std. Error t value Pr(>|t|)    
(Intercept) 34.96055    2.16454  16.151 4.91e-16 ***
wt          -3.35082    1.16413  -2.878  0.00743 ** 
disp        -0.01773    0.00919  -1.929  0.06362 .  
---
Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1

Residual standard error: 2.917 on 29 degrees of freedom
Multiple R-squared:  0.7809,	Adjusted R-squared:  0.7658 
F-statistic: 51.69 on 2 and 29 DF,  p-value: 2.744e-10


Here
- "Call" is tells us what model and data we used as input
- "Residuals" provide the descriptive statistics of the residuals. (It can give you an idea if whether the residuals are normally distributed around zero.)
- "Coefficients" provides the estimates of the coefficients as we saw before, but this time also with standard error and p-values. (The standard error says something about the uncertainty in the estimation of the parameters and can be used to create a confidence interval for the estimate of the coefficient. The p-value ("Pr(>|t|)") can be used to tell whether the coefficient is really significantly different from zero - that is whether that particular predictor variable really have an effect on the response variable.) 
- The "Adjusted R-square" is an important measure that tells us how much of the variance in the response variable that is explained by the predictor variables. (In this case 77% of the variance in the revenue is explained by the marketing total.)
- The "F-statistic" and its associated p-value is used for multiple linear regression and say something about whether there significant evidence for the relationship between the predictor values and the response variable in general

## Generalization of linear models

There are a lot of ways to generalize linear regression models:
* Transforming variables
    + Polynomial regression. We transform some of the predictor variables `x` to have `x^2`, `x^3` etc.
    + We might take the log of the response variable
    + Adstock or other transformation of the predictor variables `x`.
* *logistic regression*. Popular model class for classification tasks
* *generalized linear models*. Generalizes linear models and logistic regression models
* *penalized linear models*. Add a penalty to complex models thereby keeping models simple
* ... many many other

### *Exercise* 

Based on the `diamonds` dataset:
- build a linear regression model with the `price` variable as the response variable
- Check all the four model assumptions
- How good is you model?

It might make thins easier for plotting if you sample the dataset (for instance: `set.seed(123); dia<-diamonds[sample(1:nrow(diamonds), 2500), ]`